CREATE TABLE schema_version(version INTEGER PRIMARY KEY);
INSERT INTO schema_version VALUES(1);
CREATE TABLE users(id TEXT PRIMARY KEY, external_id TEXT NOT NULL UNIQUE, name TEXT NOT NULL, email TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE sessions(token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), csrf TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE analyses(id TEXT PRIMARY KEY, name TEXT NOT NULL, normalized_name TEXT NOT NULL UNIQUE, artifact TEXT NOT NULL, fingerprint TEXT NOT NULL, creator TEXT NOT NULL REFERENCES users(id), archived INTEGER NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL);
CREATE TABLE entities(analysis TEXT NOT NULL REFERENCES analyses(id), entity TEXT NOT NULL, workflow TEXT NOT NULL, workflow_version INTEGER NOT NULL DEFAULT 0, label TEXT, label_version INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(analysis,entity));
CREATE TABLE reviewers(analysis TEXT NOT NULL REFERENCES analyses(id), entity TEXT NOT NULL, value TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(analysis,entity));
CREATE TABLE comments(analysis TEXT NOT NULL REFERENCES analyses(id), entity TEXT NOT NULL, id TEXT NOT NULL, owner TEXT REFERENCES users(id), imported INTEGER NOT NULL DEFAULT 0, value TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(analysis,id));
CREATE TABLE history(analysis TEXT NOT NULL REFERENCES analyses(id), entity TEXT NOT NULL, id TEXT NOT NULL, value TEXT NOT NULL, PRIMARY KEY(analysis,id));
CREATE TABLE audit(analysis TEXT NOT NULL REFERENCES analyses(id), id TEXT NOT NULL, entity TEXT NOT NULL, value TEXT NOT NULL, PRIMARY KEY(analysis,id));
CREATE TABLE views(analysis TEXT NOT NULL REFERENCES analyses(id), user_id TEXT NOT NULL REFERENCES users(id), value TEXT NOT NULL, PRIMARY KEY(analysis,user_id));
CREATE TABLE receipts(user_id TEXT NOT NULL REFERENCES users(id), command TEXT NOT NULL, digest TEXT NOT NULL, outcome TEXT NOT NULL, PRIMARY KEY(user_id,command));
CREATE TABLE outbox(id TEXT PRIMARY KEY, analysis TEXT NOT NULL, value TEXT NOT NULL, published INTEGER NOT NULL DEFAULT 0);
CREATE TABLE deliveries(sequence INTEGER PRIMARY KEY, outbox_id TEXT NOT NULL UNIQUE, analysis TEXT NOT NULL, value TEXT NOT NULL);
CREATE TABLE jobs(id TEXT PRIMARY KEY, owner TEXT NOT NULL REFERENCES users(id), state TEXT NOT NULL, input TEXT, artifact TEXT, metadata TEXT NOT NULL, created INTEGER NOT NULL, expires INTEGER, error TEXT);
CREATE INDEX comment_entity ON comments(analysis,entity);
CREATE INDEX history_entity ON history(analysis,entity);
CREATE INDEX delivery_analysis ON deliveries(analysis,sequence);
CREATE INDEX job_owner ON jobs(owner,created);
CREATE INDEX outbox_analysis ON outbox(analysis);
